# Your preferred language (eng, kor, jpn, chs)
language: eng

minimum-land: 25
query-min-length: 3
price:
  per-block: 100
# White world protection can make players not able to modify land before buying
white-world-protection: []

# Shows message if player tries to modify white world
show-white-world-message: true

# Worlds which are forbidden to buy
buy-enable-worlds: []

# Prevent liquid from flowing to other land
block-flowing: true

auto-save: 300
